// File: lib/services/shop_service.dart

import 'package:petverse/core/enums/enums/app_enums.dart';
import 'package:petverse/domain/entities/shop_item_entity.dart';

class ShopService {
  static List<ShopItemEntity> getAllItems() {
    return [
      // FOOD ITEMS
      ShopItemEntity(
        id: 'food_basic_meat',
        name: 'Basic Meat',
        description: 'Simple meat that restores hunger',
        imageUrl: '🍖',
        basePrice: 10,
        currency: CurrencyType.coins,
        category: ItemCategory.food,
        rarity: ItemRarity.common,
        effects: const {ItemEffectType.hunger: 25},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_premium_steak',
        name: 'Premium Steak',
        description: 'Delicious steak that greatly restores hunger',
        imageUrl: '🥩',
        basePrice: 25,
        currency: CurrencyType.coins,
        category: ItemCategory.food,
        rarity: ItemRarity.uncommon,
        effects: const {ItemEffectType.hunger: 45, ItemEffectType.happiness: 10},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_superfood',
        name: 'Superfood',
        description: 'Magical food that boosts all stats',
        imageUrl: '⭐',
        basePrice: 2,
        currency: CurrencyType.gems,
        category: ItemCategory.food,
        rarity: ItemRarity.epic,
        effects: const {
          ItemEffectType.hunger: 50,
          ItemEffectType.happiness: 30,
          ItemEffectType.energy: 20
        },
        createdAt: DateTime.now(),
      ),

      // TOY ITEMS
      ShopItemEntity(
        id: 'toy_ball',
        name: 'Ball',
        description: 'Simple ball that makes pets happy',
        imageUrl: '⚽',
        basePrice: 15,
        currency: CurrencyType.coins,
        category: ItemCategory.toy,
        rarity: ItemRarity.common,
        effects: const {ItemEffectType.happiness: 30},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'toy_premium_rope',
        name: 'Premium Rope',
        description: 'High-quality rope toy',
        imageUrl: '🪢',
        basePrice: 35,
        currency: CurrencyType.coins,
        category: ItemCategory.toy,
        rarity: ItemRarity.rare,
        effects: const {ItemEffectType.happiness: 50, ItemEffectType.energy: -5},
        createdAt: DateTime.now(),
      ),

      // MEDICINE ITEMS
      ShopItemEntity(
        id: 'medicine_energy_drink',
        name: 'Energy Drink',
        description: 'Restores pet energy instantly',
        imageUrl: '⚡',
        basePrice: 20,
        currency: CurrencyType.coins,
        category: ItemCategory.medicine,
        rarity: ItemRarity.uncommon,
        effects: const {ItemEffectType.energy: 40},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'medicine_health_potion',
        name: 'Health Potion',
        description: 'Magical potion that restores all stats',
        imageUrl: '🧪',
        basePrice: 1,
        currency: CurrencyType.gems,
        category: ItemCategory.medicine,
        rarity: ItemRarity.rare,
        effects: const {
          ItemEffectType.hunger: 100,
          ItemEffectType.happiness: 100,
          ItemEffectType.energy: 100
        },
        createdAt: DateTime.now(),
      ),
      // FOOD (8)
      ShopItemEntity(
        id: 'food_biscuit',
        name: 'Biscuit',
        description: 'Crunchy snack for mild hunger',
        imageUrl: '🍪',
        basePrice: 8,
        currency: CurrencyType.coins,
        category: ItemCategory.food,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.hunger: 15},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_fish',
        name: 'Fresh Fish',
        description: 'A healthy meal for your pet',
        imageUrl: '🐟',
        basePrice: 18,
        currency: CurrencyType.coins,
        category: ItemCategory.food,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.hunger: 30},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_golden_apple',
        name: 'Golden Apple',
        description: 'Mystic fruit with unknown effects',
        imageUrl: '🍎',
        basePrice: 2,
        currency: CurrencyType.gems,
        category: ItemCategory.food,
        rarity: ItemRarity.epic,
        effects: {ItemEffectType.hunger: 40, ItemEffectType.health: 20},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_snack_box',
        name: 'Snack Box',
        description: 'Mixed snacks for your pet',
        imageUrl: '🥡',
        basePrice: 35,
        currency: CurrencyType.coins,
        category: ItemCategory.food,
        rarity: ItemRarity.uncommon,
        effects: {ItemEffectType.hunger: 40, ItemEffectType.happiness: 5},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_magic_cookie',
        name: 'Magic Cookie',
        description: 'Cookie that boosts XP',
        imageUrl: '✨🍪',
        basePrice: 1,
        currency: CurrencyType.gems,
        category: ItemCategory.food,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.xp: 50, ItemEffectType.hunger: 10},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_xp_burger',
        name: 'XP Burger',
        description: 'Burger that grants experience',
        imageUrl: '🍔',
        basePrice: 150,
        currency: CurrencyType.xp,
        category: ItemCategory.food,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.xp: 80},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_veggie_mix',
        name: 'Veggie Mix',
        description: 'Healthy mix of vegetables',
        imageUrl: '🥗',
        basePrice: 14,
        currency: CurrencyType.coins,
        category: ItemCategory.food,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.hunger: 25},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'food_milk',
        name: 'Milk Bottle',
        description: 'Sweet milk for energy and hunger',
        imageUrl: '🥛',
        basePrice: 18,
        currency: CurrencyType.coins,
        category: ItemCategory.food,
        rarity: ItemRarity.uncommon,
        effects: {ItemEffectType.hunger: 20, ItemEffectType.energy: 10},
        createdAt: DateTime.now(),
      ),

      // TOY (8)
      ShopItemEntity(
        id: 'toy_chew_bone',
        name: 'Chew Bone',
        description: 'Classic dog toy',
        imageUrl: '🦴',
        basePrice: 12,
        currency: CurrencyType.coins,
        category: ItemCategory.toy,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.happiness: 20},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'toy_catnip',
        name: 'Catnip',
        description: 'Irresistible for cats!',
        imageUrl: '🌿',
        basePrice: 15,
        currency: CurrencyType.coins,
        category: ItemCategory.toy,
        rarity: ItemRarity.uncommon,
        effects: {ItemEffectType.happiness: 25},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'toy_robot_mouse',
        name: 'Robot Mouse',
        description: 'A high-tech toy that boosts energy',
        imageUrl: '🤖🐭',
        basePrice: 40,
        currency: CurrencyType.coins,
        category: ItemCategory.toy,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.happiness: 50, ItemEffectType.energy: 10},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'toy_magic_yarn',
        name: 'Magic Yarn Ball',
        description: 'Yarn that enchants pets',
        imageUrl: '🧶✨',
        basePrice: 3,
        currency: CurrencyType.gems,
        category: ItemCategory.toy,
        rarity: ItemRarity.epic,
        effects: {ItemEffectType.happiness: 70, ItemEffectType.xp: 20},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'toy_frisbee',
        name: 'Frisbee',
        description: 'Great fun in the park',
        imageUrl: '🥏',
        basePrice: 20,
        currency: CurrencyType.coins,
        category: ItemCategory.toy,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.happiness: 30},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'toy_cuddle_bear',
        name: 'Cuddle Bear',
        description: 'Comfort toy for happiness',
        imageUrl: '🧸',
        basePrice: 25,
        currency: CurrencyType.coins,
        category: ItemCategory.toy,
        rarity: ItemRarity.uncommon,
        effects: {ItemEffectType.happiness: 35},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'toy_bouncing_ball',
        name: 'Bouncing Ball',
        description: 'Never gets tired!',
        imageUrl: '🏀',
        basePrice: 30,
        currency: CurrencyType.coins,
        category: ItemCategory.toy,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.happiness: 40},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'toy_mirror_box',
        name: 'Mirror Box',
        description: 'Odd toy that improves XP',
        imageUrl: '🪞📦',
        basePrice: 100,
        currency: CurrencyType.xp,
        category: ItemCategory.toy,
        rarity: ItemRarity.epic,
        effects: {ItemEffectType.xp: 100, ItemEffectType.happiness: 20},
        createdAt: DateTime.now(),
      ), // MEDICINE (8)
      ShopItemEntity(
        id: 'med_basic_pill',
        name: 'Basic Pill',
        description: 'Cura leve para pequenos problemas',
        imageUrl: '💊',
        basePrice: 20,
        currency: CurrencyType.coins,
        category: ItemCategory.medicine,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.health: 25},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'med_vitamin_pack',
        name: 'Vitamin Pack',
        description: 'Suplementos para energia e saúde',
        imageUrl: '🧃',
        basePrice: 30,
        currency: CurrencyType.coins,
        category: ItemCategory.medicine,
        rarity: ItemRarity.uncommon,
        effects: {ItemEffectType.health: 20, ItemEffectType.energy: 20},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'med_elixir',
        name: 'Elixir da Vida',
        description: 'Restaura completamente o pet',
        imageUrl: '🧴',
        basePrice: 3,
        currency: CurrencyType.gems,
        category: ItemCategory.medicine,
        rarity: ItemRarity.epic,
        effects: {
          ItemEffectType.health: 100,
          ItemEffectType.energy: 100,
          ItemEffectType.happiness: 100
        },
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'med_energy_capsule',
        name: 'Energy Capsule',
        description: 'Recupera energia rapidamente',
        imageUrl: '🔋',
        basePrice: 18,
        currency: CurrencyType.coins,
        category: ItemCategory.medicine,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.energy: 40},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'med_medic_kit',
        name: 'Medical Kit',
        description: 'Cura completa e duradoura',
        imageUrl: '🩹',
        basePrice: 1,
        currency: CurrencyType.gems,
        category: ItemCategory.medicine,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.health: 80, ItemEffectType.energy: 30},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'med_sleep_syrup',
        name: 'Sleep Syrup',
        description: 'Restaura energia e felicidade',
        imageUrl: '💤',
        basePrice: 80,
        currency: CurrencyType.xp,
        category: ItemCategory.medicine,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.energy: 60, ItemEffectType.happiness: 15},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'med_bandage_roll',
        name: 'Bandage Roll',
        description: 'Para feridas simples',
        imageUrl: '🩼',
        basePrice: 12,
        currency: CurrencyType.coins,
        category: ItemCategory.medicine,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.health: 15},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'med_magic_mist',
        name: 'Magic Mist',
        description: 'Neblina curativa rara',
        imageUrl: '🌫️✨',
        basePrice: 200,
        currency: CurrencyType.xp,
        category: ItemCategory.medicine,
        rarity: ItemRarity.epic,
        effects: {ItemEffectType.health: 100, ItemEffectType.xp: 50},
        createdAt: DateTime.now(),
      ),

      // ACCESSORY (10)
      ShopItemEntity(
        id: 'acc_red_hat',
        name: 'Red Hat',
        description: 'Bonito chapéu vermelho',
        imageUrl: '🎩',
        basePrice: 15,
        currency: CurrencyType.coins,
        category: ItemCategory.accessory,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.happiness: 10},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_cool_shades',
        name: 'Cool Shades',
        description: 'Óculos estilosos',
        imageUrl: '🕶️',
        basePrice: 25,
        currency: CurrencyType.coins,
        category: ItemCategory.accessory,
        rarity: ItemRarity.uncommon,
        effects: {ItemEffectType.happiness: 20},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_cape',
        name: 'Hero Cape',
        description: 'Capa de herói lendário',
        imageUrl: '🦸‍♂️',
        basePrice: 1,
        currency: CurrencyType.gems,
        category: ItemCategory.accessory,
        rarity: ItemRarity.epic,
        effects: {ItemEffectType.xp: 50},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_bowtie',
        name: 'Bow Tie',
        description: 'Charmoso e elegante',
        imageUrl: '🎀',
        basePrice: 10,
        currency: CurrencyType.coins,
        category: ItemCategory.accessory,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.happiness: 5},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_golden_collar',
        name: 'Golden Collar',
        description: 'Colar de ouro para pets nobres',
        imageUrl: '👑',
        basePrice: 5,
        currency: CurrencyType.gems,
        category: ItemCategory.accessory,
        rarity: ItemRarity.epic,
        effects: {ItemEffectType.happiness: 40},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_bandana',
        name: 'Colorful Bandana',
        description: 'Estilo e conforto',
        imageUrl: '🧣',
        basePrice: 20,
        currency: CurrencyType.coins,
        category: ItemCategory.accessory,
        rarity: ItemRarity.uncommon,
        effects: {ItemEffectType.happiness: 15},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_magic_collar',
        name: 'Magic Collar',
        description: 'Concede experiência extra',
        imageUrl: '💫',
        basePrice: 90,
        currency: CurrencyType.xp,
        category: ItemCategory.accessory,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.xp: 80},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_pet_armor',
        name: 'Pet Armor',
        description: 'Protege o pet com estilo',
        imageUrl: '🛡️',
        basePrice: 3,
        currency: CurrencyType.gems,
        category: ItemCategory.accessory,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.health: 50},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_earring',
        name: 'Earring',
        description: 'Brinco brilhante',
        imageUrl: '💎',
        basePrice: 22,
        currency: CurrencyType.coins,
        category: ItemCategory.accessory,
        rarity: ItemRarity.common,
        effects: {ItemEffectType.happiness: 10},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'acc_wizard_hat',
        name: 'Wizard Hat',
        description: 'Chapéu mágico',
        imageUrl: '🧙‍♂️',
        basePrice: 2,
        currency: CurrencyType.gems,
        category: ItemCategory.accessory,
        rarity: ItemRarity.epic,
        effects: {ItemEffectType.xp: 40, ItemEffectType.happiness: 20},
        createdAt: DateTime.now(),
      ),

      // SPECIAL (3)
      ShopItemEntity(
        id: 'special_lucky_charm',
        name: 'Lucky Charm',
        description: 'Traz boa sorte!',
        imageUrl: '🍀',
        basePrice: 4,
        currency: CurrencyType.gems,
        category: ItemCategory.special,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.xp: 60},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'special_time_freezer',
        name: 'Time Freezer',
        description: 'Pausa o tempo dos status',
        imageUrl: '🕰️',
        basePrice: 250,
        currency: CurrencyType.xp,
        category: ItemCategory.special,
        rarity: ItemRarity.epic,
        effects: {},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'special_portal_scroll',
        name: 'Portal Scroll',
        description: 'Usado para eventos raros',
        imageUrl: '📜',
        basePrice: 3,
        currency: CurrencyType.gems,
        category: ItemCategory.special,
        rarity: ItemRarity.epic,
        effects: {},
        createdAt: DateTime.now(),
      ),

      // DECORATION (5)
      ShopItemEntity(
        id: 'decor_flower_vase',
        name: 'Flower Vase',
        description: 'Bonito vaso de flores',
        imageUrl: '🌸',
        basePrice: 12,
        currency: CurrencyType.coins,
        category: ItemCategory.decoration,
        rarity: ItemRarity.common,
        effects: {},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'decor_wall_painting',
        name: 'Wall Painting',
        description: 'Obra de arte decorativa',
        imageUrl: '🖼️',
        basePrice: 28,
        currency: CurrencyType.coins,
        category: ItemCategory.decoration,
        rarity: ItemRarity.uncommon,
        effects: {},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'decor_pet_statue',
        name: 'Pet Statue',
        description: 'Estátua do seu pet!',
        imageUrl: '🗿',
        basePrice: 1,
        currency: CurrencyType.gems,
        category: ItemCategory.decoration,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.happiness: 10},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'decor_christmas_tree',
        name: 'Christmas Tree',
        description: 'Árvore de natal festiva',
        imageUrl: '🎄',
        basePrice: 2,
        currency: CurrencyType.gems,
        category: ItemCategory.decoration,
        rarity: ItemRarity.rare,
        effects: {ItemEffectType.happiness: 15},
        createdAt: DateTime.now(),
      ),
      ShopItemEntity(
        id: 'decor_moon_lamp',
        name: 'Moon Lamp',
        description: 'Iluminação calma para o pet',
        imageUrl: '🌕',
        basePrice: 70,
        currency: CurrencyType.xp,
        category: ItemCategory.decoration,
        rarity: ItemRarity.epic,
        effects: {ItemEffectType.energy: 10},
        createdAt: DateTime.now(),
      ),
    ];
  }

  static List<ShopItemEntity> getItemsByCategory(ItemCategory category) {
    return getAllItems().where((item) => item.category == category).toList();
  }

  static ShopItemEntity? getItemById(String itemId) {
    try {
      return getAllItems().firstWhere((item) => item.id == itemId);
    } catch (e) {
      return null;
    }
  }
}
